name: Docs Production Deployment - Netlify CLI

env:
  NODE_VERSION: 20
  DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
  DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}

on:
  # Branch filtering is not supported with `on: create`.
  push:
    branches:
      - 'prod-docs/latest'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./docs/
jobs:

  netlify-deploy:
    name: Build Docs
    needs: check-version
    if: needs.check-version.outputs.continue == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOCS_LATEST_VERSION: ${{ needs.check-version.outputs.docs_latest_version }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Docs dependencies
        run: npm ci

      - name: Docs build
        working-directory: ./docs/
        run: npm run docs:build:production:netlify

      - name: Deploy to Netlify
        run: |
          npx netlify env:set DOCS_LATEST_VERSION=$DOCS_LATEST_VERSION --context production
          npx netlify deploy --prod --prodIfUnlocked --dir .vuepress/dist/docs/ --site $NETLIFY_SITE_ID

        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DOCS_LATEST_VERSION: ${{ env.DOCS_LATEST_VERSION }}

      - name: Update Environment Variables on Netlify
        run: |
          curl -X PATCH "https://api.netlify.com/api/v1/accounts/${NETLIFY_ACCOUNT_ID}/env/DOCS_LATEST_VERSION?site_id=${NETLIFY_SITE_ID}" \
            -H "Authorization: Bearer ${NETLIFY_AUTH_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "context": "production",
              "value": "'"${DOCS_LATEST_VERSION}"'"
            }'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DOCS_LATEST_VERSION: ${{ env.DOCS_LATEST_VERSION }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_ACCOUNT_ID: handsontable-team
